spring:
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
#      ddl-auto: create-drop
      ddl-auto: validate
  datasource:
    url: jdbc:postgresql://localhost:5432/kitty_split
    username: admin
    password: password

external:
  open.exchange:
    base-url: "http://openexchangerates.org/api"
    app-id: ${OPEN_EXCHANGE_APP_ID}
