defaults:
  time.zone: Europe/Moscow

spring:
  mvc:
    format:
      offset-date-time: "yyyy-MM-dd'T'HH:mmXXX"
      big-decimal-scale: 5
  properties:
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
